### ISSUE TITLE
Open current web page in Incognito mode

### ISSUE THREAD

**Issue by nachoGitH** [musically-ut/key-ncognito#4]
This is really useful for online newspapers that create a payment wall once you visit a number of articles for free and require you to pay, or for any content sharing pages that allow you to wait long periods between downloads (combined with a VPN extension enabled in Incognito mode).

From my Chrome store review:  
It would be lovely if you could solve my worst annoyance, which is open a currently Standard browsed page in Incognito. 

Now, I have to press Ctrl+Shift+N, get back to the Standard windows, and copy or drag the URL to the Incognito Window. Many thanks

**Comment by musically-ut** [comment]
Interesting! I hadn't anticipated these use cases, thanks for bringing them to my notice. 

As for the feature of opening the current tab incognito, how would you want that feature to work? 

Do you need any functionality not provided by, say, https://chrome.google.com/webstore/detail/incognito-this/icnaplnkjfjncegmphmlfpggildllbho ?

**Comment by musically-ut** [comment]
Since the other extensions which do this have gained a dubious reputation, I think I'll actually add this functionality as an optional [Browser action](https://developer.chrome.com/extensions/browserAction) or a [Page action](https://developer.chrome.com/extensions/pageAction). I am leaning towards the latter because that allows the user to turn the functionality off from the preferences page.
